### PR TITLE
ENH: new date-based versioning; `qiime` -> `qiime2` package rename

### PR DESCRIPTION
**Pull request by thermokarst**
# ~~DO NOT MERGE~~

New date-based versioning scheme is:

- YYYY.M.patch.dev0 for development version (e.g. 2017.2.0.dev0, 2017.2.1.dev0, 2018.10.0.dev0)
- YYYY.M.patch for release version (e.g. 2017.2.0, 2017.2.1, 2018.10.0)

Plugins/interfaces are recommended to specify `qiime2 == YYYY.M.*` in setup.py's `install_requires` to obtain patch releases for a given train release.

The new versioning scheme is PEP 440 compliant.

Standardized LICENSE and copyright headers in source files.

### CODE REVIEW

**Comment by thermokarst** [comment]
Hi @BenKaehler, we had a few questions about this PR that we sent via Slack (a DM from me to you), just to let you know. Thanks!

**Comment by BenKaehler** [comment]
Thanks @thermokarst and @jairideout. There is a url that needs to change in `plugin_setup.py` as well. You could either change it in this PR or it will get picked up next time I make a PR from my fork, so no big deal. Also, I responded to your Slack DM. Thanks again.

**Comment by thermokarst** [comment]
Thanks @BenKaehler! Are you talking about [this link](https://github.com/qiime2/q2-feature-classifier/blob/master/q2_feature_classifier/plugin_setup.py#L17)? The convention that we are using (I think!) is to use the plugin repo (e.g. `https://github.com/qiime2/q2-feature-classifier`) in the `qiime2.Plugin` setup, and then `https://qiime2.org` in `setup.py`. It does look like I missed the `setup.py` tweak, so I will fix that up (and the `plugin_setup.py` change already happened in #41). Thanks!

**Comment by BenKaehler** [comment]
Thanks @thermokarst, I was working of an older fork and didn't realise that you had already fixed it. Sorry. We should be fine to merge this tomorrow, I just need to finish the conversation I was having with Gavin about it first.

**Pull request merged**
